apiVersion: batch/v1
kind: Job
metadata:
  name: kubelet-failure
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "support"
    meta.helm.sh/release-namespace: "default"
spec:
  template:
    metadata:
      labels:
        app: kubelet-failure
    spec:
      hostPID: true
      containers:
        - name: kubelet-failure
          image: busybox
          command:
            - /bin/sh
            - -c
            - "kill -9 $(pgrep kubelet) || true"
          securityContext:
            privileged: true
      restartPolicy: Never
  backoffLimit: 0
