apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-failure
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "support"
    meta.helm.sh/release-namespace: "default"
spec:
  selector:
    matchLabels:
      app: kubelet-failure
  template:
    metadata:
      labels:
        app: kubelet-failure
    spec:
      hostPID: true
      containers:
        - name: kubelet-failure
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Starting kubelet kill command"
              pgrep kubelet
              kill -9 $(pgrep kubelet) || true
              echo "Kubelet kill command executed"
              exit 0
          securityContext:
            privileged: true
      restartPolicy: OnFailure
